Tidy up scenario reports & add round 3 scenario description
covid19-forecast-hub-europe/covid19-scenario-hub-europe-website pull request #11
Opened 2022-09-05 16:52 UTC by kathsherratt

This PR aims to tidy up the website a bit. Currently there is some duplication/confusion where we have the page [Scenarios](https://covid19scenariohub.eu/scenarios.html) describing each scenario round, and a separate menu under "Reports" for the resulting [reports](https://covid19scenariohub.eu/report1.html) on rounds 1 & 2. 

This PR
- Tidies up the Scenarios page describing each round: making the descriptions consistent between each round, and using the metadata in `scenarios.R` rather than plain text
- Uses the Scenarios page as the front page for the drop-down menu for reports under this page; adds link & drop-down menu link to Round 2 report
- Tidies up `scenarios.R` metadata: adding Round 0 table, adding Round 3 metadata (table, dates etc)
- Adds Round 3 scenarios as new tab on website (Scenarios page)

The main problem is getting the Round 3 HTML scenario table to format properly - I copied from the wiki page but it doesn't format properly when knitted here. I can't immediately find how to fix this so it would really help to get some HTML knowledge if @Bisaloo could have a look!

I have tried to make this PR easier to review with commit-by-commit descriptions, hope that helps. Attached a screenshot of how the new layout for the Scenarios page looks.

![image](https://user-images.githubusercontent.com/62290797/188491850-400bf20f-bbcb-46d5-a771-f71076dda3ed.png)

2022-09-06 06:30 UTC, RokGrah commented
This looks great, @kathsherratt . I assume Hugo is the one that should, when ready, merge this pull request?

2022-09-06 06:57 UTC, sbfnk requested changes
These changes look great.

I've suggested a few small fixes which, I think, will solve the table rendering.

2022-09-06 06:57 UTC, sbfnk commented on code/load/scenarios.R
> +                   "table" = "<table> <tr>
It's a bit strange but this seems to need a new line

2022-09-06 06:57 UTC, sbfnk commented on code/load/scenarios.R
> +       <li> * Vaccination as planned = Primary schedule + 2 booster doses </li>
this one is missing a `<ul>` block

2022-09-06 06:57 UTC, sbfnk commented on code/load/scenarios.R
> +       <li> ** Seasonal vaccination campaigns: Autumn = 15 September to 15 December; Spring = 15 March to 15 June
Here and below some terminal `</li>` statements are missing.

Also need to remove all the stray asterisks as they confuse the markdown

2022-09-06 06:57 UTC, sbfnk commented on _site.yml
>        href: scenarios.html
Is the idea that people click on "Scenarios" where the menu then unfolds below to get to the definitions? It doesn't seem to work for me and I don't think it's very obvious.

Perhaps we could have an "Overview" menu item at the top that links to this page?

2022-09-07 15:29 UTC, Bisaloo approved these changes
There is a minor issue with the report from round 2 (see attached screenshot) but it's not linked with these changes. It's just an reporting artifact in the truth data.

![image](https://user-images.githubusercontent.com/10783929/188918244-5b6acb35-1d27-4bda-a98b-74cd09009bde.png)

I'm voting to merge this PR.

2022-09-08 05:39 UTC, merged